pipelines:
  - name: java_pipeline
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: myFirstRepo
            execution:
        onExecute:
           - echo '1'
        
