resources:
  - name: my_source_repo
    type: GitRepo
    configuration:
      gitProvider: alex_github
      path: alexwang66/jfrog-pipeline
      branches:
        include: main
      buildOn:
        commit:                true
 
pipelines:     
    - name: pipeline_gitrepo_trigger
      steps:
      - name: gitrepo_trigger_step_1
        type: Bash
        configuration:
          inputResources:
            - name: my_source_repo
        execution:
          onExecute:
            - printenv                  # A benign operation for the demo
